export { default as AuthController } from './AuthController'
export { default as DashboardController } from './DashboardController'
export { default as PageController } from './PageController'
export { default as ProductoController } from './ProductoController'
export { default as VentaController } from './VentaController'